# environment.yml
name: quantmsutils
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - click
  - sdrf-pipelines==0.0.33
  - pyopenms>=3.3.0
  - pandas
  - pyarrow>=16.1.0
  - scipy